version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data_pipeline
    networks:
      - default
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./db:/var/lib/postgresql/data

  python:
    container_name: python
    depends_on:
      - postgres
    build:
      dockerfile: ./.devcontainer/Dockerfile.de_project
      context: ../
    volumes:
      - ../:/de_project/
    networks:
      - default
    tty: true
    environment:
      - POSTGRES_URI=postgresql://postgres:postgres@172.19.0.2:5432/data_pipeline?schema=public
      - ENVIRONMENT=local
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default: