version: "3.9"
networks:
  default:
    name: local
    external: true

services:
  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: data_pipeline
    networks:
      - default
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./sql-init:/docker-entrypoint-initdb.d/

  python:
    container_name: python
    depends_on:
      - postgres
    build:
      dockerfile: ./.devcontainer/Dockerfile.de_project
      context: ../
    volumes:
      - ../:/de_project/
    networks:
      - default
    tty: true
    environment:
      - POSTGRES_URI=postgresql://postgres:dev@postgres:5432/data_pipeline?schema=public
      - ENVIRONMENT=local
    extra_hosts:
      - "host.docker.internal:host-gateway"